name: Github Action

on:
  pull_request:  # trigger on pull requests
  push:
    branches:
      - master    # trigger on push to master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust components
        run: rustup component add rustfmt
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Capsule
        run: cargo install ckb-capsule --locked --version 0.10.0
      
      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross --rev=6982b6c

      - name: Check Rust format
        run: cargo fmt -- --check

      - name: Build contracts
        run: |
          cd test-lib
          capsule build

      - name: Test contracts
        run: |
          cd test-lib
          capsule test
