name: Github Action

on:
  pull_request:  # trigger on pull requests
  push:
    branches:
      - master    # trigger on push to master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust components
        run: rustup component add rustfmt
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          docker_nightly_version: snapshot-20201008

      - name: Install Capsule
        run: cargo install ckb-capsule --locked --version 0.9.0

      - name: Check Rust format
        run: cargo fmt -- --check

      - name: Build contracts
        run: |
          cd test-lib
          capsule build

      - name: Test contracts
        run: |
          cd test-lib
          capsule test
